name: CI Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: windows-latest
    env:
      JAVA_VERSION: 21

    defaults:
      run:
        shell: bash
        working-directory: ./Antigravity

    steps:
      - name: Checkout code and submodule(s)
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'jetbrains'
          cache: gradle

      - name: Compile and Run Unit Tests
        run: ./gradlew :compose-desktop-touch:desktopTest

      - name: Build Demo Application and Library
        run: ./gradlew :touch-demo:packageUberJarForCurrentOS :compose-desktop-touch:assemble :compose-desktop-touch:desktopSourcesJar :compose-desktop-touch:dokkaJavadocJar

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: compose-desktop-touch-release
          path: |
            Antigravity/touch-demo/build/compose/jars/touch-demo-windows-x64-*.jar
            Antigravity/compose-desktop-touch/build/libs/compose-desktop-touch-desktop-*.jar
            Antigravity/compose-desktop-touch/build/libs/compose-desktop-touch-*-javadoc.jar
            Antigravity/compose-desktop-touch/build/libs/compose-desktop-touch-metadata-*.jar
          if-no-files-found: error

