name: CI Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: windows-latest
    env:
      JAVA_VERSION: 21

    defaults:
      run:
        shell: bash
        working-directory: ./Antigravity

    steps:
      - name: Checkout code and submodule(s)
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'jetbrains'
          cache: gradle

      - name: Compile and Run Unit Tests
        run: ./gradlew :compose-desktop-touch:desktopTest

      - name: Build Demo Application
        run: ./gradlew :touch-demo:assemble
